on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: sftp://45.33.68.85:22/var/www/html
        ftp-username: root
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        known-hosts: 68.175.143.120 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgm7kFizncSo61t9r2D5/snVfkoxaeflpLKCRqlG1uieELmwapIWYazOznSI3Yr+SgEdugJz0tC8fKb3N/j9kzSHSHBCo/up7HZSXl2/7qaftE9K9b1KHpmYKsh7iGr3wNjfT8i+MVi5r0hr8MsDe/QsgTt6gQGeDJ2XxSud3LOQhHas=
        # git-ftp-args: --insecure